import fs from 'fs';
import path from 'path';

const distDir = path.resolve('dist');
const publicDir = path.resolve('public');

const distSitemap0 = path.join(distDir, 'sitemap-0.xml');
const distSitemapIndex = path.join(distDir, 'sitemap-index.xml');
const distSitemapXml = path.join(distDir, 'sitemap.xml');
const publicSitemapXml = path.join(publicDir, 'sitemap.xml');

// 1. Ensure dist exists
if (!fs.existsSync(distDir)) {
  console.error('❌ dist/ directory not found. Run astro build first.');
  process.exit(1);
}

// 2. Read sitemap-0.xml (which contains all URLs generated by @astrojs/sitemap)
if (fs.existsSync(distSitemap0)) {
  let content = fs.readFileSync(distSitemap0, 'utf8');

  // Verify it contains <urlset>
  if (content.includes('<urlset') && content.includes('<loc>')) {
    const urlMatches = content.match(/<loc>(.*?)<\/loc>/g) || [];
    console.log(`\n--- 4WHEELS Automated Sitemap Generator ---`);
    console.log(`✅ Discovered ${urlMatches.length} pages in Astro sitemap output.`);

    // Write full urlset directly to dist/sitemap.xml
    fs.writeFileSync(distSitemapXml, content, 'utf8');
    console.log(`✅ Written full URL list to dist/sitemap.xml (${fs.statSync(distSitemapXml).size} bytes)`);

    // Write full urlset directly to public/sitemap.xml for repository persistence
    fs.writeFileSync(publicSitemapXml, content, 'utf8');
    console.log(`✅ Written full URL list to public/sitemap.xml (${fs.statSync(publicSitemapXml).size} bytes)`);

    console.log(`\n🎉 Success: https://www.4wheelspk.com/sitemap.xml now contains all ${urlMatches.length} pages directly!`);
    console.log(`Ready for immediate Google Search Console submission.\n`);
  } else {
    console.warn('⚠️ sitemap-0.xml did not contain urlset, falling back to sitemap-index.xml');
    if (fs.existsSync(distSitemapIndex)) {
      const indexContent = fs.readFileSync(distSitemapIndex, 'utf8');
      fs.writeFileSync(distSitemapXml, indexContent, 'utf8');
      fs.writeFileSync(publicSitemapXml, indexContent, 'utf8');
    }
  }
} else {
  console.error('❌ sitemap-0.xml not found in dist/.');
  process.exit(1);
}
